# Generated by Django 3.0.7 on 2020-07-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='badge',
            field=models.CharField(default='Premature Plato', max_length=20),
        ),
    ]
